// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(memory_plantFFI)
import memory_plantFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_memory_plant_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_memory_plant_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureMemoryPlantInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * On-device personal memory for a single user. Thread-safe.
 *
 * Holds two stores: the HLB fact bank (`inner`) and the document RAG store
 * (`docs`). Document embeddings are supplied by the caller (the app's own
 * embedder / on-device model) — Memory Plant does NOT bundle an embedding
 * model in the FFI, so the binding stays light and ORT-free.
 */
public protocol MemoryPlantProtocol: AnyObject, Sendable {
    
    /**
     * Index a document whose chunks are ALREADY embedded by the caller (the
     * app's embedder / on-device model). Split a big file with the top-level
     * `chunkText`, embed each chunk, then call this. `chunks` and `embeddings`
     * must be the same length; re-using `docId` replaces it. Returns the
     * number of chunks indexed.
     */
    func addDocument(docId: String, chunks: [String], embeddings: [[Float]], metadata: [String: String]) throws  -> UInt32
    
    /**
     * All stored facts: `{ "{subject}|{predicate}" -> value }`.
     */
    func exportUser() throws  -> [String: String]
    
    /**
     * Drop a document and all its chunks. Returns true if it existed.
     */
    func forgetDocument(docId: String)  -> Bool
    
    func forgetFact(predicate: String) throws  -> Bool
    
    /**
     * GDPR Article 17 — drop this user entirely (algebraic, residual ≈ 0).
     */
    func forgetUser()  -> Bool
    
    func ingestMessage(message: String) throws  -> [FactDto]
    
    /**
     * Number of indexed documents.
     */
    func nDocuments()  -> UInt32
    
    func recallFact(predicate: String) throws  -> String?
    
    /**
     * Persist facts AND documents under `path` as a **plaintext** JSON tree.
     * For privacy-first on-device storage use `saveSealed` instead.
     */
    func save(path: String) throws 
    
    /**
     * Encrypted-at-rest save (ChaCha20-Poly1305 AEAD): the whole on-disk
     * footprint — facts (values, keys, schema, service metadata) AND document
     * chunks/embeddings — is sealed; no plaintext touches disk. `key` MUST be
     * exactly 32 bytes; derive/store it in the iOS Keychain or Android
     * Keystore. Pairs with `loadOrCreateSealed`.
     */
    func saveSealed(path: String, key: Data) throws 
    
    /**
     * Semantic search over a caller-supplied query embedding, with rich
     * out-of-box filters (all ANDed): `metadata` exact-match, `containsText`
     * case-insensitive substring, `minScore` cosine threshold, `docIds`
     * restriction. Empty filters = pure top-k nearest.
     */
    func search(queryEmbedding: [Float], k: UInt32, metadata: [String: String], containsText: String?, minScore: Float?, docIds: [String]?)  -> [DocHit]
    
    func storeFact(predicate: String, value: String) throws 
    
    func totalFacts()  -> UInt64
    
}
/**
 * On-device personal memory for a single user. Thread-safe.
 *
 * Holds two stores: the HLB fact bank (`inner`) and the document RAG store
 * (`docs`). Document embeddings are supplied by the caller (the app's own
 * embedder / on-device model) — Memory Plant does NOT bundle an embedding
 * model in the FFI, so the binding stays light and ORT-free.
 */
open class MemoryPlant: MemoryPlantProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_memory_plant_fn_clone_memoryplant(self.handle, $0) }
    }
    /**
     * New, EMPTY in-memory engine (never touches disk). Use `open` for a
     * durable engine. Sane defaults: dim 512, vocab_cap 4096.
     */
public convenience init(dim: UInt32, vocabCap: UInt32, user: String) {
    let handle =
        try! rustCall() {
    uniffi_memory_plant_fn_constructor_memoryplant_new(
        FfiConverterUInt32.lower(dim),
        FfiConverterUInt32.lower(vocabCap),
        FfiConverterString.lower(user),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_memory_plant_fn_free_memoryplant(handle, $0) }
    }

    
    /**
     * Open a DURABLE engine: load the state previously written by `save` at
     * `path`, or start fresh there if none exists yet (load-or-create). This
     * closes the cross-session round-trip — `loadOrCreate(path) → … → save(path)`
     * survives a process restart, so on-device memory is persistent.
     *
     * (Named `load_or_create`, not `open`, because `open` is a reserved
     * keyword in both Swift and Kotlin and would force backtick-escaping at
     * every call site.)
     *
     * When existing state is found, its persisted `dim`/`vocab_cap` win and
     * the args here are ignored; they apply only to a fresh create.
     */
public static func loadOrCreate(path: String, dim: UInt32, vocabCap: UInt32, user: String)throws  -> MemoryPlant  {
    return try  FfiConverterTypeMemoryPlant_lift(try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_constructor_memoryplant_load_or_create(
        FfiConverterString.lower(path),
        FfiConverterUInt32.lower(dim),
        FfiConverterUInt32.lower(vocabCap),
        FfiConverterString.lower(user),$0
    )
})
}
    
    /**
     * Durable + ENCRYPTED engine: decrypt and load the sealed state at `path`
     * (written by `saveSealed`), or start fresh if none exists there. `key`
     * MUST be exactly 32 bytes and MUST match the key used to seal — a wrong
     * key fails AEAD authentication and returns an error (no silent fallback).
     * This is the recommended constructor for a privacy-first product.
     */
public static func loadOrCreateSealed(path: String, key: Data, dim: UInt32, vocabCap: UInt32, user: String)throws  -> MemoryPlant  {
    return try  FfiConverterTypeMemoryPlant_lift(try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_constructor_memoryplant_load_or_create_sealed(
        FfiConverterString.lower(path),
        FfiConverterData.lower(key),
        FfiConverterUInt32.lower(dim),
        FfiConverterUInt32.lower(vocabCap),
        FfiConverterString.lower(user),$0
    )
})
}
    

    
    /**
     * Index a document whose chunks are ALREADY embedded by the caller (the
     * app's embedder / on-device model). Split a big file with the top-level
     * `chunkText`, embed each chunk, then call this. `chunks` and `embeddings`
     * must be the same length; re-using `docId` replaces it. Returns the
     * number of chunks indexed.
     */
open func addDocument(docId: String, chunks: [String], embeddings: [[Float]], metadata: [String: String])throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_method_memoryplant_add_document(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),
        FfiConverterSequenceString.lower(chunks),
        FfiConverterSequenceSequenceFloat.lower(embeddings),
        FfiConverterDictionaryStringString.lower(metadata),$0
    )
})
}
    
    /**
     * All stored facts: `{ "{subject}|{predicate}" -> value }`.
     */
open func exportUser()throws  -> [String: String]  {
    return try  FfiConverterDictionaryStringString.lift(try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_method_memoryplant_export_user(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Drop a document and all its chunks. Returns true if it existed.
     */
open func forgetDocument(docId: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_memory_plant_fn_method_memoryplant_forget_document(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(docId),$0
    )
})
}
    
open func forgetFact(predicate: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_method_memoryplant_forget_fact(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(predicate),$0
    )
})
}
    
    /**
     * GDPR Article 17 — drop this user entirely (algebraic, residual ≈ 0).
     */
open func forgetUser() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_memory_plant_fn_method_memoryplant_forget_user(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func ingestMessage(message: String)throws  -> [FactDto]  {
    return try  FfiConverterSequenceTypeFactDto.lift(try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_method_memoryplant_ingest_message(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(message),$0
    )
})
}
    
    /**
     * Number of indexed documents.
     */
open func nDocuments() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_memory_plant_fn_method_memoryplant_n_documents(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func recallFact(predicate: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_method_memoryplant_recall_fact(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(predicate),$0
    )
})
}
    
    /**
     * Persist facts AND documents under `path` as a **plaintext** JSON tree.
     * For privacy-first on-device storage use `saveSealed` instead.
     */
open func save(path: String)throws   {try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_method_memoryplant_save(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),$0
    )
}
}
    
    /**
     * Encrypted-at-rest save (ChaCha20-Poly1305 AEAD): the whole on-disk
     * footprint — facts (values, keys, schema, service metadata) AND document
     * chunks/embeddings — is sealed; no plaintext touches disk. `key` MUST be
     * exactly 32 bytes; derive/store it in the iOS Keychain or Android
     * Keystore. Pairs with `loadOrCreateSealed`.
     */
open func saveSealed(path: String, key: Data)throws   {try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_method_memoryplant_save_sealed(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),
        FfiConverterData.lower(key),$0
    )
}
}
    
    /**
     * Semantic search over a caller-supplied query embedding, with rich
     * out-of-box filters (all ANDed): `metadata` exact-match, `containsText`
     * case-insensitive substring, `minScore` cosine threshold, `docIds`
     * restriction. Empty filters = pure top-k nearest.
     */
open func search(queryEmbedding: [Float], k: UInt32, metadata: [String: String], containsText: String?, minScore: Float?, docIds: [String]?) -> [DocHit]  {
    return try!  FfiConverterSequenceTypeDocHit.lift(try! rustCall() {
    uniffi_memory_plant_fn_method_memoryplant_search(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(queryEmbedding),
        FfiConverterUInt32.lower(k),
        FfiConverterDictionaryStringString.lower(metadata),
        FfiConverterOptionString.lower(containsText),
        FfiConverterOptionFloat.lower(minScore),
        FfiConverterOptionSequenceString.lower(docIds),$0
    )
})
}
    
open func storeFact(predicate: String, value: String)throws   {try rustCallWithError(FfiConverterTypeMpError_lift) {
    uniffi_memory_plant_fn_method_memoryplant_store_fact(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(predicate),
        FfiConverterString.lower(value),$0
    )
}
}
    
open func totalFacts() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_memory_plant_fn_method_memoryplant_total_facts(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMemoryPlant: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MemoryPlant

    public static func lift(_ handle: UInt64) throws -> MemoryPlant {
        return MemoryPlant(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MemoryPlant) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MemoryPlant {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MemoryPlant, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemoryPlant_lift(_ handle: UInt64) throws -> MemoryPlant {
    return try FfiConverterTypeMemoryPlant.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemoryPlant_lower(_ value: MemoryPlant) -> UInt64 {
    return FfiConverterTypeMemoryPlant.lower(value)
}




/**
 * A document-search hit returned by `search`. Metadata values are stringified.
 */
public struct DocHit: Equatable, Hashable {
    public var chunkId: String
    public var docId: String
    public var score: Float
    public var text: String
    public var metadata: [String: String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chunkId: String, docId: String, score: Float, text: String, metadata: [String: String]) {
        self.chunkId = chunkId
        self.docId = docId
        self.score = score
        self.text = text
        self.metadata = metadata
    }

    

    
}

#if compiler(>=6)
extension DocHit: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocHit {
        return
            try DocHit(
                chunkId: FfiConverterString.read(from: &buf), 
                docId: FfiConverterString.read(from: &buf), 
                score: FfiConverterFloat.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                metadata: FfiConverterDictionaryStringString.read(from: &buf)
        )
    }

    public static func write(_ value: DocHit, into buf: inout [UInt8]) {
        FfiConverterString.write(value.chunkId, into: &buf)
        FfiConverterString.write(value.docId, into: &buf)
        FfiConverterFloat.write(value.score, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterDictionaryStringString.write(value.metadata, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocHit_lift(_ buf: RustBuffer) throws -> DocHit {
    return try FfiConverterTypeDocHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocHit_lower(_ value: DocHit) -> RustBuffer {
    return FfiConverterTypeDocHit.lower(value)
}


public struct FactDto: Equatable, Hashable {
    public var subject: String
    public var predicate: String
    public var obj: String
    public var source: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(subject: String, predicate: String, obj: String, source: String) {
        self.subject = subject
        self.predicate = predicate
        self.obj = obj
        self.source = source
    }

    

    
}

#if compiler(>=6)
extension FactDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFactDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FactDto {
        return
            try FactDto(
                subject: FfiConverterString.read(from: &buf), 
                predicate: FfiConverterString.read(from: &buf), 
                obj: FfiConverterString.read(from: &buf), 
                source: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FactDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.subject, into: &buf)
        FfiConverterString.write(value.predicate, into: &buf)
        FfiConverterString.write(value.obj, into: &buf)
        FfiConverterString.write(value.source, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFactDto_lift(_ buf: RustBuffer) throws -> FactDto {
    return try FfiConverterTypeFactDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFactDto_lower(_ value: FactDto) -> RustBuffer {
    return FfiConverterTypeFactDto.lower(value)
}


public enum MpError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Memory(msg: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension MpError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMpError: FfiConverterRustBuffer {
    typealias SwiftType = MpError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MpError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Memory(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MpError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Memory(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpError_lift(_ buf: RustBuffer) throws -> MpError {
    return try FfiConverterTypeMpError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMpError_lower(_ value: MpError) -> RustBuffer {
    return FfiConverterTypeMpError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionFloat: FfiConverterRustBuffer {
    typealias SwiftType = Float?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterFloat.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterFloat.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDocHit: FfiConverterRustBuffer {
    typealias SwiftType = [DocHit]

    public static func write(_ value: [DocHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDocHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DocHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [DocHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDocHit.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFactDto: FfiConverterRustBuffer {
    typealias SwiftType = [FactDto]

    public static func write(_ value: [FactDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFactDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FactDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [FactDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFactDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [[Float]]

    public static func write(_ value: [[Float]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[Float]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[Float]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
/**
 * Split a large file/text into overlapping word-window chunks (pure Rust, no
 * model needed). Embed each chunk with your own model, then `addDocument`.
 */
public func chunkText(text: String, chunkSize: UInt32, chunkOverlap: UInt32) -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_memory_plant_fn_func_chunk_text(
        FfiConverterString.lower(text),
        FfiConverterUInt32.lower(chunkSize),
        FfiConverterUInt32.lower(chunkOverlap),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_memory_plant_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_memory_plant_checksum_func_chunk_text() != 46396) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_add_document() != 25136) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_export_user() != 25242) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_forget_document() != 40957) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_forget_fact() != 7281) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_forget_user() != 13245) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_ingest_message() != 57551) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_n_documents() != 58161) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_recall_fact() != 49521) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_save() != 4065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_save_sealed() != 64130) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_search() != 25442) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_store_fact() != 62977) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_method_memoryplant_total_facts() != 981) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_constructor_memoryplant_load_or_create() != 39311) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_constructor_memoryplant_load_or_create_sealed() != 13083) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memory_plant_checksum_constructor_memoryplant_new() != 40197) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureMemoryPlantInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all